apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: senha123
            - name: MYSQL_DATABASE
              value: meubanco
          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: mysql-dados
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-dados
          persistentVolumeClaim:
            claimName: mysql-dados

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: eduardopetrocchi/projeto-backend:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
